services:
  postgresql:
      image: postgres:16-alpine
      container_name: postgresql
      environment:
        POSTGRES_PASSWORD: dupa1234
        PGDATA: /var/lib/postgresql/data
      ports:
        - 5432:5432
      volumes: 
        - /var/storage/postgres_data/:/var/lib/postgresql/data